language: node_js
sudo: false
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
git:
  - depth: 3
node_js:
  - "6"
install:
  - npm install
  - yarn global add polymer-cli
  - npm install -g firebase-tools
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
after_success:
  - ./scripts/deploy.sh
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
  - $HOME/.nvm
